### ISSUE TITLE
I am unable to share session

### ISSUE THREAD

**Issue by mfaizanshaikh** [sourcey/symple-server#8]
I started redis server, gave proper servername and port. 

but i am unable to create a new Symple client. it says Authentication failed: Missing user or token param.

Can you please explain what i am missing ?

**Comment by auscaster** [comment]
You need to provide either a token or user param when creating the client, like so:

```
client = new Symple.Client({
  token: 'someauthtoken',      <--- this
  peer: {
    user: 'myusername',          <--- or this
  }
});
```

**Comment by mfaizanshaikh** [comment]
Thanks. It did solve the authenticate problem.

**Comment by mfaizanshaikh** [comment]
However i am encountering another issue. 

When i open multiple tabs with same user then the roster gets multiple entries of same user. 

Can you please advise ?

**Comment by auscaster** [comment]
All browser sessions are individual and will be stored in the roster. Its
up to you how you display that on the UI.
